### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by RedsaphirCZ** [coolsquid/SquidUtils#43]
Hello CoolSquid,
long time ago I found, that your mod (squidUtils or squidApi) is messing up Project red textures...dont know why and it is still happening.
Here are all information that i have, if you need something else, please tell me.
https://github.com/MrTJP/ProjectRed/issues/844

Keep up the good work :)

**Comment by coolsquid** [comment]
I see. ProjectRed is storing their block icons' simple names, and adding the modid prefix when registering them. Not really that much I can do.

**Comment by coolsquid** [comment]
I've found a solution, but the next version might not be out before in a few weeks or months.

There's one thing you could try temporarily though. Open Blocks.cfg, replace all references to "texture=ProjRed|.*:" (without quotes, enable regex) with "texture=" (without the quotes).

**Comment by MrTJP** [comment]
Shouldn't really matter, there isn't a 'convention' for registering texture names. What is squidutils doing to the textures that would cause this issue anyway?  

I know my blocks have weird names (projectred.module.blockname) because I started doing that when I first started the mod, and don't know how to change them without screwing up current worlds, but textures are registered with simple names.

**Comment by coolsquid** [comment]
The mod has been rewritten for 1.9, and 1.7.10 is no longer supported. Textures are no longer touched by SquidUtils in 1.9, so the issue is no longer applicable.
